backend_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }

backend_security_login:
    path:     /login
    defaults: { _controller: BackendBundle:Security:login }

backend_security_logout:
    path:     /logout

backend_estado:
    resource: "@BackendBundle/Resources/config/routing/estado.yml"
    prefix:   /estado
