backend_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }

backend_security_login:
    path:     /login
    defaults: { _controller: BackendBundle:Security:login }

backend_security_logout:
    path:     /logout

backend_estado:
    resource: "@BackendBundle/Resources/config/routing/estado.yml"
    prefix:   /estado

backend_local:
    resource: "@BackendBundle/Resources/config/routing/local.yml"
    prefix:   /local

backend_tipo_activo:
    resource: "@BackendBundle/Resources/config/routing/tipo-activo.yml"
    prefix:   /tipo-activo

backend_tipo_resultado:
    resource: "@BackendBundle/Resources/config/routing/tipo-resultado.yml"
    prefix:   /tipo-resultado

backend_rol:
    resource: "@BackendBundle/Resources/config/routing/rol.yml"
    prefix:   /rol

backend_responsable:
    resource: "@BackendBundle/Resources/config/routing/responsable.yml"
    prefix:   /responsable

backend_revision:
    resource: "@BackendBundle/Resources/config/routing/revision.yml"
    prefix:   /revision

backend_metadata:
    resource: "@BackendBundle/Resources/config/routing/metadata.yml"
    prefix:   /metadata

backend_auditoria:
    resource: "@BackendBundle/Resources/config/routing/auditoria.yml"
    prefix:   /auditoria