frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Default:index }

frontend_homepage_pdf:
    path:     /pdf
    defaults: { _controller: FrontendBundle:Default:pdf }

frontend_homepage_excel:
    path:     /excel
    defaults: { _controller: FrontendBundle:Default:excel }

frontend_homepage_excel2:
    path:     /excel2
    defaults: { _controller: FrontendBundle:Default:excel2 }

frontend_homepage_excel_at1:
    path:     /excel-at1
    defaults: { _controller: FrontendBundle:Default:excelAT1 }

frontend_homepage_excel_rotos:
    path:     /excel-rotos
    defaults: { _controller: FrontendBundle:Default:excelEquiposRotos }

frontend_excel_baja:
    path:     /excel-baja
    defaults: { _controller: FrontendBundle:Default:excelBaja }

frontend_homepage_angular:
    path:     /angular
    defaults: { _controller: FrontendBundle:Default:angular }

frontend_security_login:
    path:     /login
    defaults: { _controller: "FrontendBundle:Security:login" }

frontend_security_logut:
    path:     /logout

frontend_apunte:
    resource: "@FrontendBundle/Resources/config/routing/apunte.yml"
    prefix:   /apunte

frontend_activo_fijo:
    resource: "@FrontendBundle/Resources/config/routing/activo-fijo.yml"
    prefix:   /activo-fijo

frontend_informe:
    resource: "@FrontendBundle/Resources/config/routing/informe.yml"
    prefix:   /informe
