metadata_index:
    path:     /
    defaults: { _controller: "CommonBundle:Metadata:index" }
    methods:  GET

metadata_show:
    path:     /{id}/show
    defaults: { _controller: "CommonBundle:Metadata:show" }
    methods:  GET

metadata_new:
    path:     /new
    defaults: { _controller: "CommonBundle:Metadata:new" }
    methods:  [GET, POST]

metadata_edit:
    path:     /{id}/edit
    defaults: { _controller: "CommonBundle:Metadata:edit" }
    methods:  [GET, POST]

metadata_delete:
    path:     /{id}/delete
    defaults: { _controller: "CommonBundle:Metadata:delete" }
    methods:  DELETE
