activo_fijo_index:
    path:     /
    defaults: { _controller: "FrontendBundle:ActivoFijo:index" }
    methods:  GET

activo_fijo_filter:
    path:     /filter
    defaults: { _controller: "FrontendBundle:ActivoFijo:filter" }
    methods:  [GET, POST]

activo_fijo_by_apuntes:
    path:     /por-apuntes
    defaults: { _controller: "FrontendBundle:ActivoFijo:byApuntes" }
    methods:  [GET, POST]

activo_fijo_show:
    path:     /{id}/show
    defaults: { _controller: "FrontendBundle:ActivoFijo:show" }
    methods:  GET
    options:
        expose: true

#activo_fijo_new:
#    path:     /new
#    defaults: { _controller: "FrontendBundle:ActivoFijo:new" }
#    methods:  [GET, POST]

activo_fijo_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontendBundle:ActivoFijo:edit" }
    methods:  [GET, POST]
    options:
        expose: true

#activo_fijo_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "FrontendBundle:ActivoFijo:delete" }
#    methods:  DELETE
