apunte_index:
    path:     /
    defaults: { _controller: "FrontendBundle:Apunte:index" }
    methods:  GET

apunte_show:
    path:     /{id}/show
    defaults: { _controller: "FrontendBundle:Apunte:show" }
    methods:  GET

apunte_new:
    path:     /{idActivo}/new
    defaults: { _controller: "FrontendBundle:Apunte:new" }
    methods:  [GET, POST]

apunte_new_control:
    path:     /{idActivo}/control
    defaults: { _controller: "FrontendBundle:Apunte:newControl" }
    methods:  [GET, POST]
    options:
        expose: true

apunte_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontendBundle:Apunte:edit" }
    methods:  [GET, POST]

apunte_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontendBundle:Apunte:delete" }
    methods:  [GET]

apunte_delete_from_aft:
    path:     /{id}/delete-from-aft/{idActivo}
    defaults: { _controller: "FrontendBundle:Apunte:deleteFromAft" }
    methods:  [GET]
