metadata_index:
    path:     /
    defaults: { _controller: "BackendBundle:Metadata:index" }
    methods:  GET

metadata_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Metadata:show" }
    methods:  GET

#metadata_new:
#    path:     /new
#    defaults: { _controller: "BackendBundle:Metadata:new" }
#    methods:  [GET, POST]
#
#metadata_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "BackendBundle:Metadata:edit" }
#    methods:  [GET, POST]
#
#metadata_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "BackendBundle:Metadata:delete" }
#    methods:  [GET]
